<?php
return [
    [
        'id'=>1,
        'echogram_id'=>1,
        'measure_2d_ivsd'=>13.6,
        'measure_2d_ivss'=>floatval(27),
        'measure_2d_lvidd'=>49.1,
        'measure_2d_lvids'=>19.8,
        'measure_2d_lvpwd'=>22.9,
        'measure_2d_lvpws'=>floatval(29),
        'measure_2d_aordiam'=>36.6,
        'measure_2d_ladimen'=>44.6,
        'measure_2d_lvotdiam'=>null,
        'measure_2d_laperao'=>1.2,
        'measure_2d_lavi'=>39.07,
        'measure_2d_lvmassindex'=>226,
        'measure_2d_edvteich'=>113.5,
        'measure_2d_esvteich'=>floatval(12),
        'measure_2d_fs'=>59.7,
        'measure_2d_tapse'=>floatval(26),
        'measure_2d_efteich'=>floatval(89),
        'measure_2d_efsimpbiplane'=>floatval(55),
        'measure_2d_efsimp4ch'=>null,
        'measure_2d_efsimp2ch'=>null,
        'measure_2d_ivcins'=>null,
        'measure_2d_ivcexp'=>null
    ],
];
